[workspace]
members = ["rustigc",
	   "rustigc-tools",
	   "rustigc-py",
	   "rustigc-wasm"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
license = "GPL-2.0-or-later WITH Classpath-exception-2.0"
authors = ["Jerome Brunet <jbrun3t@gmail.com>"]
repository = "https://github.com/jbrun3t/rustigc"
keywords = ["igc", "soaring", "aviation", "gps"]
categories = ["parser-implementations", "aerospace"]

# Important so LLVM properly re-partition inlining
[profile.release]
codegen-units = 1

[profile.profiling]
inherits = "release"
lto = "thin"
debug = true             # Full debug info for symbols
strip = false           # Don't strip symbols
