[package]
name = "rustigc"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "IGC flight log parsing and cross-country scoring"
readme = "README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
crazy-test = []
geojson = ["dep:geojson"]

[dependencies]
btoi = "0.4"
geographiclib-rs = "0.2"
geojson = { version = "1.0", default-features = false, optional = true }
jiff = "0.2"
log = "0.4"
num-traits = "0.2"
rstar = "0.12"
rustc-hash = "1.1"
serde = { version = "1.0", features = ["derive"], optional = true }
smallvec = "1.15"
thiserror = "2.0"
utz = { version = "0.4", default-features = false, features = ["core", "custom", "geom-varint-arcs"]}
winnow = "0.7"

[dev-dependencies]
pretty_assertions = "1"
criterion = "0.5"
rustigc = { path = ".", features = ["serde", "geojson"] }
serde_json = "1"


[[bench]]
name = "benches"
harness = false
