[package]
name = "rustigc-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "GPL-2.0-or-later"
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "CLI tools for IGC file parsing and analysis"
readme = "README.md"

[lib]
name = "rustigc_tools"
path = "src/lib.rs"

[[bin]]
name = "rustigc-parse"
path = "src/main.rs"

[[bin]]
name = "rustigc-xc-score"
path = "src/score.rs"

[dependencies]
log = "0.4"
env_logger = "0.11"
rustigc = { path = "../rustigc", version = "0.0.4", features = ["serde", "geojson"] }
clap = { version = "4", features = ["derive"] }
serde_json = "1"
jiff = "0.2"
utz = { version = "0.4", default-features = false, features = ["core", "tiny-static"] }
