[package]
name = "rustigc-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "GPL-2.0-or-later"
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "CLI tools for IGC file parsing and analysis"
readme = "README.md"

[[bin]]
name = "rustigc"
path = "src/main.rs"

[dependencies]
log = "0.4"
env_logger = "0.11"
rustigc = { path = "../rustigc", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
serde_json = "1"
